### ISSUE TITLE
Add links to Blockstack meetups

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-site#106]
Would be cool to add links to the blockstack meetup groups from blockstack.org so that people can find them easily.

**Comment by shea256** [comment]
Yeah great call @larrysalibra.

We can add a link to the topics page for Blockstack meetups: http://www.meetup.com/topics/blockstack/.

We'll do this with the next update to the website, which should be coming this week.

**Comment by guylepage3** [comment]
I will also set this up on http://github.com/blockstack/community today.

**Comment by guylepage3** [comment]
Closing this issue
