### ISSUE TITLE
request: new labels

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-site#112]
@shea256 can we also create the following labels for this repo;
- design
- html/css
- production

Thanks.

**Comment by guylepage3** [comment]
@shea256 new label request..
* copywriting

**Comment by guylepage3** [comment]
@shea256 can we add a `copywriting` label to this repo?

**Comment by shea256** [comment]
Done! @guylepage3 you really don't have the ability to create new labels? You're in the admin group for this repo.

**Comment by guylepage3** [comment]
Perfect. thank you sir.
