### ISSUE TITLE
Create new favicon (windows .ico)

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-site#117]
Create new favicon for windows .ico file format
* 16x16
* 32x32
* 48x48
* 256x256

**Comment by guylepage3** [comment]
@shea256 here's the new favicon for the blockstack.org 
[favicon.ico.zip](https://github.com/blockstack/blockstack-site/files/443658/favicon.ico.zip)

**Comment by shea256** [comment]
Love seeing the new favicon in the browser. Closing this issue.
