### ISSUE TITLE
Add Chain to list of sponsors

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-site#39]
Add the Chain logo to the list of sponsors.

**Comment by willykaram** [comment]
If helpful, I can also write up some documentation for the ReadMe on how best for people to contribute -- not sure if this is the preferred approach to follow, but seems in keeping w/other patches/contributions so far.

**Comment by john-light** [comment]
@willykaram that would be great, it's pretty simple right now:  
- If you see an issue, open an issue and state whether you're working on a solution or not, and if you're working on a solution, what the solution is  
- When you think you've solved an open issue, send a PR  

Most of the time I skip opening an issue and just open a PR, but that's just me.
