### ISSUE TITLE
Site broken

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-site#4]
<img width="1280" alt="screen shot 2015-08-10 at 3 55 32 pm" src="https://cloud.githubusercontent.com/assets/597182/9162431/632b616c-3f78-11e5-84ac-de891d06dba5.png">

Same on Desktop Safari & Firefox.

**Comment by larrysalibra** [comment]
3rd party Typekit script isn't loading
<img width="1276" alt="screen shot 2015-08-10 at 3 35 15 pm" src="https://cloud.githubusercontent.com/assets/597182/9162747/a143c920-3f79-11e5-9ef1-9be746004c06.png">

**Comment by larrysalibra** [comment]
Mobile shows similar problems but different content using different network. Images uploaded here due to github s3 issues: https://blockstack.slack.com/archives/blockstack-site/p1439194510000191

Looks like the site is being served by a CDN and the cache might not have gotten cleared.

**Comment by guylepage3** [comment]
@larrysalibra the typekit error you're seeing never goes away. It's a bug that has been with typekit for a year now. So that's actually not an issue. Something else seems to be going wrong at the moment.

**Comment by guylepage3** [comment]
Just confirmed. AWS servers are down for typekit. See typekit blog for updates. http://status.typekit.com 

![image](https://cloud.githubusercontent.com/assets/1711854/9169453/4dc9a490-3f29-11e5-9813-8b41dd0bcf51.jpg)
