### ISSUE TITLE
Add "Log in" to chat.blockstack.org

### ISSUE THREAD

**Issue by john-light** [blockstack/blockstack-site#58]
Add "log in" button to chat.blockstack.org linking to blockstack.slack.com

![untitled 1](https://cloud.githubusercontent.com/assets/9424721/10371791/0371aad8-6db3-11e5-90eb-66a058e419ac.jpg)

**Comment by guylepage3** [comment]
Wow. Haha. Great catch @john-light.

**Comment by guylepage3** [comment]
Hm.. Will have to look into this more as this is a Slack API. @john-light do you have any examples of others doing this?

**Comment by muneeb-ali** [comment]
It's using a Slackin server (which in turn uses the Slack API). Current version uses [this fork](https://github.com/muneeb-ali/slackin) which is a slight modification from original. And adding a login button there should be fairly easy (you can send a pull request on my fork).

**Comment by guylepage3** [comment]
Thanks @muneeb-ali, will do..

**Comment by guylepage3** [comment]
@john-light, @muneeb-ali and I looked into this and Muneeb says, at some point we can just replace the  slackin app with a simple python/flask app that talks to Slack’s API so we can add in that login button.

**Comment by john-light** [comment]
@guylepage3 you can create a button and link it to blockstack.slack.com.

**Comment by john-light** [comment]
can change "or" to "Already have an account?" button:[LOG IN HERE]

**Comment by shea256** [comment]
There's now a tiny "sign in" button, much nicer :)

Closing this issue.
