### ISSUE TITLE
Apply the latest bootstrap v4.0.0-alpha to React

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-site#63]
Apply the latest bootstrap v4.0.0-alpha to React. In doing so the following issues will be resolved; 
- https://github.com/blockstack/blockstack-site/issues/32
- https://github.com/blockstack/blockstack-site/issues/33

**Comment by shea256** [comment]
This is an old issue, so I'm going to close it.

We're already using Bootstrap v4 and it seems to be working great.
