### ISSUE TITLE
Installation instructions need updating

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-site#70]
In the [installation instructions](https://github.com/blockstack/blockstack-site/blob/master/app/docs/installation.md) we currently mention brew and apt-get. Brew install doesn't exist yet and needs to be removed and apt-get install will need to get updated (on our repository) if we want to keep it. I actually think that for Linux

```
$ sudo apt-get update && sudo apt-get install -y python-pip python-dev libssl-dev
$ sudo pip install blockstack --upgrade
```

is an easier way to install than first updating the apt-get repository. It'd be different if our package was indexed by some major repository server.

**Comment by shea256** [comment]
OK I can remove `apt-get` and `brew` and if we have those options later we can always add them back in.

**Comment by john-light** [comment]
One more update I would add here is that for Debian/Linux it says:

> If you're on Debian or Ubuntu, you may have to run another command before you perform the installation shown above. To prevent any installation issues, run the following first:

I think that if you expect someone to enter a command first then it should be first in the list of things to do. Instead right now that part is at the bottom of the page.

**Comment by guylepage3** [comment]
closing issue
