### ISSUE TITLE
Some comments on the homepage

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-site#71]
Just going over the current homepage. First of all, awesome job! It's very clear and crisp. 

1. We might want to rename "Domains registered" to "Names registered" because people will like to see "proof" of this and most of our registrations are in the .id namespace. Names, to me, sounds like a more generic thing than domain names. Also, given that people would like to see the "proof" of all these registrations, we might want to make this a link e.g., to [resolver](http://resolver.onename.com/v2/namespace). The downside is that we probably don't want people to click and go away but I feel it's very powerful if they see that so many names have been registered using Blockstack. I can very quickly change the formatting of that endpoint and we can also rename the URL used for the endpoint as well. 

2. Add "Read Paper" next to "Star Blockstack on Github". The idea there is that we're very quickly saying, here is the code and here is the research paper. It's actually rare to have both. Most research papers don't have working code and vice versa. So having both things there is powerful. 

PS: Great job on getting that Github star icon in there. Looks great.

**Comment by shea256** [comment]
1a. Good call. I actually was just thinking the same thing.
1b. Yes I agree. How about I post an issue on the resolver for updating the endpoint?
2. Good call, I think this is a great place to put it.

Thanks! And great work @guylepage3 for the stellar layout!

**Comment by muneeb-ali** [comment]
Sounds good about issue on resolver. It should be a quick fix at my end.

**Comment by guylepage3** [comment]
@shea256 Thank you sir! (hat tip)

**Comment by shea256** [comment]
@muneeb-ali is there a latest copy of the paper stored somewhere on GitHub?

**Comment by shea256** [comment]
@guylepage3 can you work on adding a link to the paper to the bar with the GitHub stars in it?

**Comment by guylepage3** [comment]
@shea256 will do.

**Comment by guylepage3** [comment]
>Add "Read Paper" next to "Star Blockstack on Github". The idea there is that we're very quickly saying, here is the code and here is the research paper. It's actually rare to have both. Most research papers don't have working code and vice versa. So having both things there is powerful.

I feel this should be it's own button/section. Kind of important that viewers click on it. No?

**Comment by guylepage3** [comment]
Resolved.
