### ISSUE TITLE
Blockstack Docs mobile issue

### ISSUE THREAD

**Issue by john-light** [blockstack/blockstack-site#84]
The pictures are not resizing for mobile (viewed on Firefox for Android)

![screenshot_2016-03-14-11-59-30-1](https://cloud.githubusercontent.com/assets/9424721/13756376/ddb22470-e9dc-11e5-9315-74a9fff40443.png)

**Comment by shea256** [comment]
Thanks for reporting @john-light.

@guylepage3 the images were working earlier right? Did something break or are we missing certain device settings?

**Comment by guylepage3** [comment]
@john-light thanks for catching this.

@shea256 it looks as though something has broke. I will get on this now.

**Comment by guylepage3** [comment]
@shea256 item has been resolved. please push latest design commit live
https://github.com/blockstack/blockstack-site/commit/b3a0ee11312731277623ad12d838407cfdbf6478

**Comment by shea256** [comment]
OK will do.

**Comment by shea256** [comment]
Pushed live!
