### ISSUE TITLE
home page has two scroll bars

### ISSUE THREAD

**Issue by john-light** [blockstack/blockstack-site#99]
See screenshot, right side of the screen:

![blockstackhome](https://cloud.githubusercontent.com/assets/9424721/14945128/bf25309e-0fbe-11e6-9822-18d3a46b36c8.png)

**Comment by guylepage3** [comment]
Hmm. What browser and version are you using @john-light?

**Comment by john-light** [comment]
@guylepage3 Chromium v49.0.2623.108

**Comment by guylepage3** [comment]
I am assuming you are using a PC? If so, can you inspect element and screen shot the <html>, then <body>, then first <div>?

**Comment by guylepage3** [comment]
@john-light found the issue. resolving it now.

**Comment by guylepage3** [comment]
Resolved https://github.com/blockstack/blockstack-site/commit/b8625dfa45392c43e748f8f4cd6402c73f71292a
